apiVersion: v1
kind: Pod
metadata:
  name: curl-debug
  labels:
    app: curl-debug
spec:
  containers:
    - name: curl-debug-container
      image: lmacademy/alpine-curl:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"


