apiVersion: v1
kind: Service
metadata: 
  name: pvc-color-api-headless-svc
spec:
  clusterIP: None # This is used to create a headless service
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: color-api
