apiVersion: v1
kind: Namespace
metadata: 
  name: dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1" # 1000m
    requests.memory: "1Gi"
    limits.cpu: "2" # 2000m 
    limits.memory: "2Gi" 
