apiVersion: v1
kind: Service
metadata:
  name: bookyland-external-name
spec:
  type: ExternalName
  externalName: google.com # This is the DNS name to which the service will resolve (no https:// prefix or http:// prefix)
