apiVersion: v1
kind: Service
metadata:
  name: bookyland-node-port-svc # Name of the service
  labels:
    app: bookyland-api-node-port # Label for the service, can be used to select this service in other resources
spec:
  type: NodePort # Type of service, NodePort allows external access to the service
  selector:
    app: bookyland-api # This label should match the label in the pod template of the deployment (pods to expose)
  ports:
    - port: 8000 # Port exposed by the service
      targetPort: 8000 # Port on the pod that the service will forward traffic to
      nodePort: 30007 # Node port to access the service externally, must be in the range 30000-32767
