apiVersion: v1
kind: Pod
metadata:
  name: busybox-secrets-retrieving
  labels:
    app: busybox-secrets-retrieving
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command: ["/bin/sh", "-c", "sleep 1800"]
      volumeMounts:
        - name: db-credentials-volume
          mountPath: /etc/db-credentials
          readOnly: true
      resources:
        limits: 
          memory: 100Mi
          cpu: "500m"
  volumes:
    - name: db-credentials-volume
      secret:
        secretName: db-credentials
        # items:
        #   - key: username
        #     path: dev/username # This is the path where the secret will be mounted and pod path will be /etc/db-credentials/dev/username
        #   - key: password
        #     path: dev/password # This is the path where the secret will be mounted and pod path will be /etc/db-credentials/dev/password

