apiVersion: v1
kind: Pod
metadata:
  name: busybox-secrets-retrieving
  labels:
    app: busybox-secrets-retrieving
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command: ["/bin/sh", "-c", "echo $DB_USERNAME && echo $DB_PASSWORD && sleep 1800"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-credentials
      # Alternative way to retrieve secrets, that entails to use the name as they were created 'username' and 'password'
      # envFrom:
      #   - secretRef:
      #       name: db-credentials
      resources:
        limits: 
          memory: 100Mi
          cpu: "500m"
