apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password

    [client]
    default-character-set=utf8

    [mysql]
    default-character-set=utf8

    [mysqldump]
    default-character-set=utf8

    [mysqld]
    character-set-server=utf8

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |
    -- Add your MySQL initialization SQL commands here
    CREATE USER 'bookyland_user_dev'@'%' IDENTIFIED BY '@qwerqwerjklweriuyqwe87';
    GRANT ALL PRIVILEGES ON bookyland.* TO 'bookyland_user_dev'@'%';
    FLUSH PRIVILEGES;

