
import os

# MONGODB
DATABASE_HOST = os.getenv('DATABASE_HOST', 'localhost')
DATABASE_NAME = os.getenv('DATABASE_NAME', 'bookyland')
DATABASE_PORT = int(os.getenv('DATABASE_PORT', 27017))
DATABASE_USER = os.getenv('MONGODB_USER', '')
DATABASE_PASSWORD = os.getenv('MONGODB_PASSWORD', '')

# TEST FAILS
DELAY_STARTUP = os.getenv('DELAY_STARTUP', False)
FAIL_LIVENESS = os.getenv('FAIL_LIVENESS', False)
FAIL_READINESS = os.getenv('FAIL_READINESS', False)

# TEST CONFIG MAP FROM k8s
CONFIG_MAP_FILE_PATH = os.getenv('CONFIG_MAP_FILE_PATH', None)
CONFIG_MAP_MESSAGE = os.getenv('CONFIG_MAP_MESSAGE', None)
