apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev # Specify the namespace where the Pod will be created
  labels:
    app: color-api
spec:
  containers:
    - name: bookyland
      image: garavirod/bookyland-k8s:4.0.0
      ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  namespace: dev # Specify the namespace where the Service will be created
spec:
  type: ClusterIP
  selector:
    app: color-api # Match the label of the Pod
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP    
