 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: bookyland-deploy
   labels:
     app: bookyland-api
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: bookyland-api
   template:
     metadata:
       labels:
         app: bookyland-api
     spec:
       containers:
         - name: bookyland-api
           image: garavirod/bookyland-k8s:5.0.2
           ports:
             - containerPort: 8000
           env:
            - name: DATABASE_HOST
              value: mongodb-statefulset-0.mongodb-svc.default.svc.cluster.local
            - name: DATABASE_NAME
              value: bookyland
            - name: DATABASE_PORT
              value: "27017"
            - name: MONGODB_USER 
              valueFrom:
                secretKeyRef:
                  name: mongodb-bookyland-cred
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-bookyland-cred
                  key: password
           resources:
              limits:
                cpu: 500m
                memory: 128Mi

          
