apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-bookyland-db
  labels:
    app: mongodb
data: 
  mongo-init.js: | # This is the script that will be used to initialize the database
    // This is the javascript script that will be used to initialize the mongo database
    const dbName = process.env.DB_NAME;
    const dbUser = process.env.DB_USER;
    const dbPassword = process.env.DB_PASSWORD;

    db = db.getSiblingDB(dbName);

    print('INITIALIZING: ' + dbName);
    print('INITIALIZING: Creating user ' + dbUser);

    db.createUser({
        user: dbUser,
        pwd: dbPassword,
        roles: [
            {
                role: 'readWrite',
                db: dbName
            }
        ]
    });

    print("Database initialization completed!");
