apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
    - port: 27017 # port where mongodb listens by default
      targetPort: 27017
  selector:
    app: mongodb
