apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: garavirod/bookyland-k8s:4.2.0
      ports:
        - containerPort: 8000
      env:
        - name: DELAY_STARTUP
          value: "false"
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
      startupProbe:
        httpGet: 
          path: /health
          port: 8000
        failureThreshold: 2 # Number of failures before giving up
        periodSeconds: 3 # How often to perform the probe
