apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: garavirod/bookyland-k8s:4.2.1
      ports:
        - containerPort: 8000
      env:
        - name: DELAY_STARTUP
          value: 'false'
        - name: FAIL_LIVENESS
          value: 'false'
        - name: FAIL_READINESS
          value: 'true'
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
      livenessProbe:
        httpGet: 
          path: /health
          port: 8000
        failureThreshold: 3 # Number of failures before giving up
        periodSeconds: 10 # How often to perform the probe
