apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookyland-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bookyland-k8s
  template:
    metadata:
      labels:
        app: bookyland-k8s
    spec:
      containers:
      - name: bookyland-k8s
        image: garavirod/bookyland-k8s:4.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
