apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-set-0-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce # Single node access, this is basically a directory inside the node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ss-0 # Path on the host machine where the volume is located. Tis path already exists on the host machine.  
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["minikube"] # This ensures that the volume is only accessible on the minikube node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-set-1-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce # Single node access, this is basically a directory inside the node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ss-1 # Path on the host machine where the volume is located. Tis path already exists on the host machine.  
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["minikube"] # This ensures that the volume is only accessible on the minikube node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-set-2-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce # Single node access, this is basically a directory inside the node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: 
    path: /mnt/disks/ss-2 # Path on the host machine where the volume is located. Tis path already exists on the host machine.  
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["minikube"] # This ensures that the volume is only accessible on the minikube node
