apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-demo
spec:
  serviceName: busybox-service
  replicas: 2
  selector: # This is used to select the pods that are part of the stateful set
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox-container
          image: busybox:1.36.1
          command: ["sh", "-c", "sleep 3600"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: local-volume # This is the name of the volume defined in the PersistentVolumeClaim
              mountPath: /mnt/local # This is the path inside the container where the volume will be mounted
            # - name: local-volume2 # This is the name of the volume defined in the PersistentVolumeClaim
            #   mountPath: /mnt/local2 # This is the path inside the container where the volume will be mounted
  volumeClaimTemplates: # This is used to create the volumes for the pods automatically
    - metadata:
        name: local-volume # This is the name of the volume that will be created for the pods
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard # # local-storage for static volume (needs to be created manually into the cluster)
        resources:
          requests:
            storage: 128Mi
    # - metadata:
    #     name: local-volume2 # This is the name of the volume that will be created for the pods
    #   spec:
    #     accessModes:
    #       - ReadWriteOnce
    #     storageClassName: local-storage
    #     resources:
    #       requests:
    #         storage: 128Mi
