apiVersion: v1
kind: Pod
metadata:
  name: bookyland-deployment
  labels:
    app: bookyland-api
spec:
  containers:
  - name: bookyland-api-server
    image: garavirod/bookyland-k8s:4.0.0
    imagePullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8000
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: database_user
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: database_name
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: database_user_password
  - name: my-eval-mysql
    image: datascientest/mysql-k8s:1.0.0
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - containerPort: 3306
